import type { WorldState } from "./worldTypes";

export const initialWorld: WorldState = {
  turn: 0,
  timeSeconds: 0,
  alertLevel: "calm",
  suspicion: 10,
  objective: { targetHandled: false, cleanExit: true, evidenceRisk: 0 },
  player: {
    traceRisk: 0,
    stress: 20,
    permissions: ["access_guest_terminal", "access_security_camera"],
  },
  locations: {
    lobby: {
      id: "lobby",
      name: "Lobby",
      x: 420,
      y: 300,
      connectedTo: ["bar", "gallery"],
      crowdLevel: 50,
      noiseLevel: 35,
      lightLevel: 80,
      restricted: false,
      watchedBy: ["guard"],
      cameras: [],
      objects: ["guest_list_terminal"],
      npcsPresent: ["guard", "guest"],
      agentsPresent: ["face"],
      tags: ["public", "crowded"],
    },
    bar: {
      id: "bar",
      name: "Bar",
      x: 260,
      y: 300,
      connectedTo: ["lobby", "kitchen"],
      crowdLevel: 35,
      noiseLevel: 30,
      lightLevel: 75,
      restricted: false,
      watchedBy: ["waiter"],
      cameras: [],
      objects: ["wine_glass", "wine_bottle", "cleaning_cart"],
      npcsPresent: ["waiter", "cleaner"],
      agentsPresent: [],
      tags: ["public"],
    },
    kitchen: {
      id: "kitchen",
      name: "Kitchen",
      x: 100,
      y: 300,
      connectedTo: ["bar"],
      crowdLevel: 5,
      noiseLevel: 40,
      lightLevel: 70,
      restricted: true,
      watchedBy: [],
      cameras: [],
      objects: ["waiter_uniform", "power_panel", "kitchen_door"],
      npcsPresent: [],
      agentsPresent: ["runner"],
      tags: ["staff_only", "restricted"],
    },
    gallery: {
      id: "gallery",
      name: "Gallery",
      x: 580,
      y: 300,
      connectedTo: ["lobby", "balcony"],
      crowdLevel: 45,
      noiseLevel: 25,
      lightLevel: 85,
      restricted: false,
      watchedBy: ["guard"],
      cameras: ["hallway_camera"],
      objects: ["hallway_camera"],
      npcsPresent: ["target"],
      agentsPresent: [],
      tags: ["public", "quiet"],
    },
    balcony: {
      id: "balcony",
      name: "Balcony",
      x: 740,
      y: 300,
      connectedTo: ["gallery"],
      crowdLevel: 5,
      noiseLevel: 10,
      lightLevel: 55,
      restricted: false,
      watchedBy: ["guard"],
      cameras: [],
      objects: ["balcony_rail"],
      npcsPresent: [],
      agentsPresent: [],
      tags: ["private", "quiet"],
    },
  },
  npcs: {
    target: {
      id: "target",
      name: "Victor Vale",
      role: "target",
      location: "gallery",
      attentionMode: "socializing",
      suspicionTowardPlayer: 0,
      suspicionTowardAgents: {},
      beliefs: [
        { id: "event_safe", subject: "event", predicate: "is_safe", confidence: 80 },
      ],
      motives: [
        { id: "privacy", description: "Prefers private conversations.", weight: 70 },
        { id: "business_deal", description: "Interested in confidential art deals.", weight: 80 },
      ],
      permissions: [],
      stateTags: [],
      routeBias: {},
    },
    guard: {
      id: "guard",
      name: "Mara Quinn",
      role: "guard",
      location: "lobby",
      attentionMode: "watching_security",
      attentionTarget: "gallery",
      suspicionTowardPlayer: 0,
      suspicionTowardAgents: {},
      beliefs: [],
      motives: [{ id: "security", description: "Prevent security breaches.", weight: 90 }],
      permissions: [],
      stateTags: [],
      routeBias: {},
    },
    waiter: {
      id: "waiter",
      name: "Leo Sato",
      role: "service",
      location: "bar",
      attentionMode: "idle",
      suspicionTowardPlayer: 0,
      suspicionTowardAgents: {},
      beliefs: [],
      motives: [{ id: "service", description: "Keep bar stocked.", weight: 80 }],
      permissions: ["serve_drinks", "enter_bar", "enter_kitchen"],
      stateTags: [],
      routeBias: {},
    },
    cleaner: {
      id: "cleaner",
      name: "Nia Cross",
      role: "cleaner",
      location: "bar",
      attentionMode: "idle",
      suspicionTowardPlayer: 0,
      suspicionTowardAgents: {},
      beliefs: [],
      motives: [{ id: "cleanliness", description: "Respond to spills.", weight: 90 }],
      permissions: [],
      stateTags: [],
      routeBias: {},
    },
    guest: {
      id: "guest",
      name: "Guest Cluster",
      role: "guest",
      location: "lobby",
      attentionMode: "socializing",
      suspicionTowardPlayer: 0,
      suspicionTowardAgents: {},
      beliefs: [],
      motives: [{ id: "curiosity", description: "Watch disturbances.", weight: 60 }],
      permissions: [],
      stateTags: [],
      routeBias: {},
    },
  },
  agents: {
    face: {
      id: "face",
      name: "Face",
      location: "lobby",
      coverIdentity: "event_fixer",
      stress: 20,
      exposure: 0,
      skills: ["social", "deception"],
      availableTools: [
        "create_complaint",
        "impersonate_staff",
        "lure_with_private_meeting",
        "redirect_guard_attention",
      ],
      permissions: [],
      status: "idle",
      stateTags: [],
    },
    runner: {
      id: "runner",
      name: "Runner",
      location: "kitchen",
      stress: 30,
      exposure: 0,
      skills: ["stealth", "physical"],
      availableTools: [
        "impersonate_staff",
        "spill_drink",
        "move_cleaning_cart",
        "disable_power_panel",
        "tamper_balcony_rail",
        "stage_accident",
      ],
      permissions: [],
      status: "idle",
      stateTags: [],
    },
  },
  objects: {
    guest_list_terminal: {
      id: "guest_list_terminal",
      name: "Guest List Terminal",
      type: "terminal",
      location: "lobby",
      visible: true,
      portable: false,
      state: { locked: false, modified: false },
      affordances: ["modify_guest_list"],
      tags: ["admin"],
    },
    wine_glass: {
      id: "wine_glass",
      name: "Wine Glass",
      type: "drink",
      location: "bar",
      visible: true,
      portable: true,
      state: { spilled: false, clean: true },
      affordances: ["spill_drink"],
      tags: ["service"],
    },
    wine_bottle: {
      id: "wine_bottle",
      name: "Wine Bottle",
      type: "drink",
      location: "bar",
      visible: true,
      portable: true,
      state: { premium: true, poisoned: false, poison_served: false },
      affordances: ["prepare_poisoned_drink"],
      tags: ["service"],
    },
    waiter_uniform: {
      id: "waiter_uniform",
      name: "Waiter Uniform",
      type: "uniform",
      location: "kitchen",
      visible: true,
      portable: true,
      state: { available: true },
      affordances: ["impersonate_staff"],
      tags: ["disguise"],
    },
    cleaning_cart: {
      id: "cleaning_cart",
      name: "Cleaning Cart",
      type: "cart",
      location: "bar",
      visible: true,
      portable: false,
      state: { blockingSightline: false },
      affordances: ["move_cleaning_cart"],
      tags: ["cover"],
    },
    power_panel: {
      id: "power_panel",
      name: "Power Panel",
      type: "power",
      location: "kitchen",
      visible: true,
      portable: false,
      state: { powerStable: true },
      affordances: ["disable_power_panel"],
      tags: ["maintenance"],
    },
    balcony_rail: {
      id: "balcony_rail",
      name: "Balcony Rail",
      type: "rail",
      location: "balcony",
      visible: true,
      portable: false,
      state: { tampered: false },
      affordances: ["tamper_balcony_rail", "stage_accident"],
      tags: ["accident"],
    },
    hallway_camera: {
      id: "hallway_camera",
      name: "Hallway Camera",
      type: "camera",
      location: "gallery",
      visible: true,
      portable: false,
      state: { active: true, recordingSuppressed: false, powerMode: "main" },
      affordances: ["suppress_camera_record"],
      tags: ["security"],
    },
    target_phone: {
      id: "target_phone",
      name: "Target Phone",
      type: "phone",
      location: "target_inventory",
      visible: false,
      portable: false,
      owner: "target",
      state: { reachable: true },
      affordances: ["spoof_message"],
      tags: ["information"],
    },
    kitchen_door: {
      id: "kitchen_door",
      name: "Kitchen Door",
      type: "door",
      location: "bar",
      visible: true,
      portable: false,
      state: { locked: false },
      affordances: [],
      tags: ["access"],
    },
  },
  eventLog: [],
};

export function cloneWorld(world: WorldState = initialWorld): WorldState {
  return structuredClone(world);
}
