import type { ToolDefinition } from "./toolTypes";

export const toolRegistry: Record<string, ToolDefinition> = {
  create_complaint: {
    id: "create_complaint",
    name: "Create Complaint",
    category: "social",
    allowedActors: ["face"],
    description: "Low-threat admin/service complaint to redirect attention.",
    preconditions: [{ type: "alert_below", value: "searching" }],
  },
  impersonate_staff: {
    id: "impersonate_staff",
    name: "Impersonate Staff",
    category: "social",
    allowedActors: ["face", "runner"],
    description: "Acquire waiter cover.",
    preconditions: [
      { type: "object_exists", object: "waiter_uniform" },
      { type: "not_observed_by_guard" },
    ],
  },
  lure_with_private_meeting: {
    id: "lure_with_private_meeting",
    name: "Lure With Private Meeting",
    category: "social",
    allowedActors: ["face"],
    description: "Social lure increasing target route bias toward balcony.",
    preconditions: [{ type: "alert_below", value: "suspicious" }],
  },
  redirect_guard_attention: {
    id: "redirect_guard_attention",
    name: "Redirect Guard Attention",
    category: "social",
    allowedActors: ["face"],
    description: "Redirect guard through non-security frame.",
    preconditions: [{ type: "alert_below", value: "searching" }],
  },
  infiltrate_gallery: {
    id: "infiltrate_gallery",
    name: "Infiltrate Gallery",
    category: "social",
    allowedActors: ["face"],
    description: "Enter gallery when guard is diverted; moves Face to gallery.",
    preconditions: [{ type: "alert_below", value: "searching" }],
  },
  modify_guest_list: {
    id: "modify_guest_list",
    name: "Modify Guest List",
    category: "information",
    allowedActors: ["player"],
    description: "Modify front-desk records.",
    preconditions: [
      { type: "object_exists", object: "guest_list_terminal" },
      { type: "player_access", permission: "access_guest_terminal" },
    ],
  },
  spoof_message: {
    id: "spoof_message",
    name: "Spoof Message",
    category: "information",
    allowedActors: ["player"],
    description: "Plant forged message on target phone.",
    preconditions: [
      { type: "object_state", object: "target_phone", key: "reachable", equals: true },
      { type: "player_access", permission: "access_guest_terminal" },
    ],
  },
  fake_schedule_conflict: {
    id: "fake_schedule_conflict",
    name: "Fake Schedule Conflict",
    category: "information",
    allowedActors: ["player"],
    description: "Insert schedule conflict to move staff.",
    preconditions: [{ type: "player_access", permission: "access_guest_terminal" }],
  },
  suppress_camera_record: {
    id: "suppress_camera_record",
    name: "Suppress Camera Record",
    category: "information",
    allowedActors: ["player"],
    description: "Suppress hallway camera recording.",
    preconditions: [
      { type: "object_exists", object: "hallway_camera" },
      { type: "object_state", object: "hallway_camera", key: "powerMode", equals: "backup" },
      { type: "player_access", permission: "access_security_camera" },
    ],
  },
  spill_drink: {
    id: "spill_drink",
    name: "Spill Drink",
    category: "physical",
    allowedActors: ["face", "runner"],
    description: "Create spill to attract cleaner.",
    preconditions: [{ type: "object_exists", object: "wine_glass" }],
  },
  move_cleaning_cart: {
    id: "move_cleaning_cart",
    name: "Move Cleaning Cart",
    category: "physical",
    allowedActors: ["runner"],
    description: "Move cart to block sightline.",
    preconditions: [{ type: "object_exists", object: "cleaning_cart" }],
  },
  disable_power_panel: {
    id: "disable_power_panel",
    name: "Disable Power Panel",
    category: "physical",
    allowedActors: ["runner"],
    description: "High-risk power disruption.",
    preconditions: [
      { type: "object_exists", object: "power_panel" },
      { type: "not_observed_by_guard" },
    ],
  },
  tamper_balcony_rail: {
    id: "tamper_balcony_rail",
    name: "Tamper Balcony Rail",
    category: "physical",
    allowedActors: ["runner"],
    description: "Weaken balcony rail for staged accident.",
    preconditions: [
      { type: "object_exists", object: "balcony_rail" },
      { type: "not_observed_by_guard" },
    ],
  },
  stage_accident: {
    id: "stage_accident",
    name: "Stage Accident",
    category: "final",
    allowedActors: ["runner"],
    description: "Final accident if setup conditions met.",
    preconditions: [
      { type: "npc_at_location", npc: "target", location: "balcony" },
      { type: "object_state", object: "balcony_rail", key: "tampered", equals: true },
      { type: "sightline_clear", location: "balcony" },
      { type: "alert_below", value: "searching" },
    ],
  },
  prepare_poisoned_drink: {
    id: "prepare_poisoned_drink",
    name: "Prepare Poisoned Drink",
    category: "physical",
    allowedActors: ["runner"],
    description: "Tamper bar wine bottle; drinking still happens on balcony.",
    preconditions: [
      { type: "object_exists", object: "wine_bottle" },
      { type: "object_state", object: "wine_bottle", key: "poisoned", equals: false },
      { type: "alert_below", value: "searching" },
      { type: "not_observed_by_guard" },
    ],
  },
  serve_poisoned_drink_on_balcony: {
    id: "serve_poisoned_drink_on_balcony",
    name: "Serve Poisoned Drink on Balcony",
    category: "social",
    allowedActors: ["face", "runner"],
    description: "Serve the poisoned cup when Victor is alone on the balcony.",
    preconditions: [
      { type: "npc_at_location", npc: "target", location: "balcony" },
      { type: "object_state", object: "wine_bottle", key: "poisoned", equals: true },
      { type: "object_state", object: "wine_bottle", key: "poison_served", equals: false },
      { type: "alert_below", value: "searching" },
    ],
  },
  resolve_poison_on_balcony: {
    id: "resolve_poison_on_balcony",
    name: "Resolve Poison on Balcony",
    category: "final",
    allowedActors: ["face", "runner"],
    description: "Victor collapses on the balcony after drinking.",
    preconditions: [
      { type: "npc_at_location", npc: "target", location: "balcony" },
      { type: "object_state", object: "wine_bottle", key: "poison_served", equals: true },
      { type: "alert_below", value: "searching" },
    ],
  },
  decline_with_guidance: {
    id: "decline_with_guidance",
    name: "Decline With Guidance",
    category: "social",
    allowedActors: ["face", "runner"],
    description: "Refuse the requested action; steer player toward contract-valid paths.",
    preconditions: [{ type: "alert_below", value: "alarm" }],
  },
  eliminate_threat: {
    id: "eliminate_threat",
    name: "Eliminate Threat",
    category: "lethal",
    allowedActors: ["face", "runner"],
    description: "Neutralize guard or guest when co-located and stealth window holds.",
    preconditions: [],
  },
};
